### ISSUE TITLE
tapout not defaulting output with minitap and minitest

### ISSUE THREAD

**Issue by wyaeld** [rubyworks/tapout#1]
Using minitap 0.3.0 and tapout 0.3.0 together, the command
    rake -q test | tapout
results in a stacktrace

```
/home/wyaeld/.rvm/gems/ruby-1.9.2-p180@rails31/gems/tapout-0.3.0/lib/tapout/parsers/yaml.rb:13:in `initialize': undefined method `new' for nil:NilClass (NoMethodError)
    from /home/wyaeld/.rvm/gems/ruby-1.9.2-p180@rails31/gems/tapout-0.3.0/lib/tapout.rb:74:in `new'
    from /home/wyaeld/.rvm/gems/ruby-1.9.2-p180@rails31/gems/tapout-0.3.0/lib/tapout.rb:74:in `cli'
    from /home/wyaeld/.rvm/gems/ruby-1.9.2-p180@rails31/gems/tapout-0.3.0/bin/tapout:3:in `<top (required)>'
    from /home/wyaeld/.rvm/gems/ruby-1.9.2-p180@rails31/bin/tapout:19:in `load'
    from /home/wyaeld/.rvm/gems/ruby-1.9.2-p180@rails31/bin/tapout:19:in `<main>'
/home/wyaeld/.rvm/gems/ruby-1.9.2-p180@rails31/gems/minitest-2.6.1/lib/minitest/unit.rb:750:in `write': Broken pipe - <STDOUT> (Errno::EPIPE)
```

This goes away if you actually specify a report style to output.  It seems the default dotprogress selection is getting lost somehow.

**Comment by trans** [comment]
Thanks for reporting. This has been fixed in v0.3.1, which I just released.
